usage:
  # definition of software deployment method:
  # at least conda, singularity, or both
  software-stack-deployment:
    conda: true
    singularity: false
    singularity+conda: false
  report: true
