
# project_config: /research/home/sreichl/projects/imstruct/config/atac_atacseq_config.yaml
# project_config: /research/home/sreichl/projects/titans/config/atac_atacseq_config.yaml
project_config: /research/home/sreichl/projects/atacseq_pipeline/test/BSA_0000_test_hg38_atac_atacseq_config.yaml
# project_config: /research/home/sreichl/projects/atacseq_pipeline/test/BSA_0000_test_mm10_atac_atacseq_config.yaml

# The following section contains resource files required by the pipeline
# adapter_fasta: ''
adapter_fasta: /research/lab_bsf/resources/atacseq/nextera_adapters.fa
bowtie2_index:
    hg38: /nobackup/lab_bsf/resources/genomes/hg38/indices_for_Bowtie2/hg38
    mm10: /nobackup/lab_bsf/resources/genomes/mm10/indices_for_Bowtie2/mm10
chromosome_sizes:
    hg38: /research/lab_bsf/resources/atacseq/hg38.chromSizes
    mm10: /research/lab_bsf/resources/atacseq/mm10.chromSizes
blacklisted_regions:
    hg38: /research/lab_bsf/resources/atacseq/hg38-ENCODE_blacklist.sorted.v3.bed
    mm10: /research/lab_bsf/resources/atacseq/mm10-ENCODE_blacklist.sorted.v2.bed
whitelisted_regions:
    hg38: /research/lab_bsf/resources/atacseq/hg38-ENCODE_whitelist.sorted.v3.bed
    mm10: /research/lab_bsf/resources/atacseq/mm10-ENCODE_whitelist.sorted.v2.bed
unique_tss:
    hg38: /research/lab_bsf/resources/atacseq/hg38_gencode_tss_unique.sorted.bed
    mm10: /research/lab_bsf/resources/atacseq/mm10_CCDS_tss_unique.bed
regulatory_regions:
    hg38: /research/lab_bsf/resources/atacseq/homo_sapiens.GRCh38.Regulatory_Build.regulatory_features.chromosomes_only.20161111.bed
    mm10: /research/lab_bsf/resources/atacseq/mus_musculus.GRCm38.Regulatory_Build.regulatory_features.20161111.sorted.bed
genome_sizes:
    hg38: 2747877777
    mm10: 2407883318
mitochondria_names:
    hg38: chrM
    mm10: chrM
genome_fasta:
    hg38: /nobackup/lab_bsf/resources/genomes/hg38/hg38.fa
    mm10: /nobackup/lab_bsf/resources/genomes/mm10/mm10.fa
gencode_gtf:
    hg38: /research/lab_bsf/resources/atacseq/gencode.v38.basic.annotation.gtf
    mm10: /research/lab_bsf/resources/atacseq/gencode.vM25.chr_patch_hapl_scaff.basic.annotation.gtf
# gtf files generated by running /workflow/scripts/parse_reg_build_file.py on gff.gz files from http://www.ensembl.org/
regulatory_build_gtf:
    hg38: /research/lab_bsf/resources/atacseq/homo_sapiens.GRCh38.Regulatory_Build.regulatory_features.20210107.gtf
    mm10: /research/lab_bsf/resources/atacseq/mus_musculus.GRCm38.Regulatory_Build.regulatory_features.20180516.gtf

data_sources:
  # specify the ABSOLUTE PATH of input files using variable path expressions
  # entries correspond to values in the data_source column in sample_annotation table
  # {variable} can be used to replace environment variables or other sample_annotation columns
  # If you use {variable} codes, you should quote the field so python can parse it.
  bsf: /nobackup/lab_bsf/samples/{flowcell}/{flowcell}_{lane}samples/{flowcell}{lane}#{BSF_name}.bam
  bsf_test: /nobackup/lab_bsf/users/berguener/junk/atac_test_data/{flowcell}_{lane}#{BSF_name}.bam
  imstruct: /research/lab_bock/projects/imstruct/data/MJ_041_ATACSEQ_L5362/{bam}

# cluster parameters
partition: 'shortq'
memory: '32G'
threads: 2